=== AbstractSDK/schemas/metadata-schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://example.com/example.json",
  "type": "object",
  "default": {},
  "title": "Root Schema",
  "required": [
    "name",
    "description",
    "docs",
    "website",
    "type",
    "icon"
  ],
  "properties": {
    "name": {
      "type": "string",
      "default": "",
      "title": "The name Schema",
      "examples": [
        "Version Control"
      ]
    },
    "description": {
      "type": "string",
      "default": "",
      "title": "The description Schema for short descriptions.",
      "examples": [
        "Manage versions of smart-contracts on-chain"
      ]
    },
    "docs": {
      "type": "string",
      "default": "",
      "title": "The docs Schema",
      "examples": [
        "https://docs.rs/abstract-os/latest/abstract_os/os_factory/index.html"
      ]
    },
    "website": {
      "type": "string",
      "default": "",
      "title": "The website Schema",
      "examples": [
        "https://abstract.money"
      ]
    },
    "readme": {
      "type": "string",
      "default": "",
      "title": "Readme Link",
      "examples": [
        "https://raw.githubusercontent.com/AbstractSDK/abstract/main/modules/contracts/adapters/dex/README.md"
      ]
    },
    "type": {
      "type": "string",
      "enum": [
        "app",
        "adapter",
        "native",
        "core",
        "standalone"
      ],
      "default": "",
      "title": "Type of module",
      "examples": [
        "app",
        "adapter"
      ]
    },
    "icon": {
      "type": "string",
      "default": "",
      "title": "ReactIcon",
      "examples": [
        "GiTrade"
      ]
    },
    "enabled": {
      "type": "boolean",
      "default": false,
      "title": "Whether your module is enabled in the UI",
      "examples": [
        true
      ]
    }
  },
  "examples": [
    {
      "name": "Dex",
      "description": "Interact with multiple dexes",
      "docs": "https://docs.rs/abstract-os/latest/abstract_os/dex/index.html",
      "readme": "https://raw.githubusercontent.com/AbstractSDK/abstract/main/modules/contracts/adapters/dex/README.md",
      "website": "https://abstract.money",
      "type": "adapter",
      "icon": "GiTrade",
      "enabled": true
    }
  ]
}

=== AbstractSDK/schemas/abstract/etf/metadata.json
{
  "name": "ETF",
  "description": "Manage assets in your vault like an ETF.",
  "docs": "https://docs.abstract.money/tutorials/managed-etf",
  "website": "https://abstract.money",
  "type": "app",
  "icon": "RiStockLine",
  "readme": "https://raw.githubusercontent.com/AbstractSDK/abstract/main/modules/contracts/apps/etf/README.md"
}

=== AbstractSDK/schemas/abstract/cw-staking/metadata.json
{
  "name": "Cw Staking",
  "description": "Stake stake stake",
  "docs": "",
  "website": "https://fortytwo.finance",
  "type": "adapter",
  "icon": "GiTrade",
  "enabled": true,
  "readme": "https://raw.githubusercontent.com/AbstractSDK/abstract/main/modules/contracts/adapters/cw-staking/README.md"
}
